# Generated by Django 3.0.5 on 2020-07-06 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='가게명')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for alias', unique=True, verbose_name='SLUG')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='위치')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='연락처')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('store_image', models.ImageField(blank=True, upload_to='store/store_pic')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('restaurant', '음식집'), ('bar', '술집'), ('cafe', '카페')], max_length=10)),
                ('running_time', models.CharField(blank=True, max_length=30, verbose_name='영업시간')),
                ('like_users', models.ManyToManyField(related_name='like_stores', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게',
                'ordering': ['-like_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='메뉴')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='설명')),
                ('food_image', models.ImageField(blank=True, upload_to='store/menu_pic')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='가게명')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
            },
        ),
    ]
