# Generated by Django 3.0.5 on 2020-06-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
