# Generated by Django 3.0.5 on 2020-06-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_menu_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, upload_to='store/store_pic'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_image',
            field=models.ImageField(blank=True, upload_to='store/menu_pic'),
        ),
    ]
