# Generated by Django 3.0.5 on 2020-06-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
