# Generated by Django 2.2.4 on 2019-08-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190828_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agree',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
