# Generated by Django 3.0.5 on 2020-06-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190905_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='faFT',
        ),
    ]
