# Generated by Django 2.2.4 on 2019-08-22 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190402_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '투표', 'verbose_name_plural': '투표'},
        ),
    ]
