# Generated by Django 2.1.7 on 2019-04-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='foods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Store'),
        ),
    ]
