# Generated by Django 2.1.7 on 2019-04-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190417_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='foods',
            new_name='store',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.CharField(default='입력', max_length=50),
        ),
        migrations.AddField(
            model_name='menu',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
