# Generated by Django 2.2.4 on 2019-09-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_store_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '메뉴', 'verbose_name_plural': '메뉴'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '가게', 'verbose_name_plural': '가게'},
        ),
    ]
