# Generated by Django 2.2.4 on 2019-09-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboard',
            name='hits',
            field=models.IntegerField(blank=True, null=True, verbose_name='좋아요'),
        ),
    ]
