# Generated by Django 3.0.5 on 2020-05-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190905_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userboard',
            old_name='mail',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='userboard',
            name='memo',
        ),
    ]
