# Generated by Django 3.0.5 on 2020-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200521_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboard',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
    ]
