# Generated by Django 3.0.5 on 2020-05-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200521_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboard',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
