# Generated by Django 3.0.5 on 2020-06-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200525_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userboard',
            options={'ordering': ['-created_date'], 'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
    ]
