# Generated by Django 3.0.5 on 2020-06-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200601_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userboard',
            options={'ordering': ['-created_dt'], 'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.RenameField(
            model_name='userboard',
            old_name='created_date',
            new_name='created_dt',
        ),
        migrations.AddField(
            model_name='userboard',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
